name: ppsite
favicon: null
layout_spectrum: 0.9386574542149901
typography_spectrum: 0.8668647820595652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24477130500599742
  lightness: 0.8551214660983533
  saturation: 0.6357668633572757
  rhythmicContrast: 0.4342470106203109
purpose: []
